/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author roban
 */
public class JFrameImagen extends javax.swing.JFrame {

    /**
     * Creates new form JFrameImagen
     */
    public JFrameImagen(Image imagen) {
        initComponents();
        
        // Obtener un tono random de la imagen
        int w = imagen.getWidth(null);
        int h = imagen.getHeight(null);
        Image escalada = 
                herramientas.HerramientasImagen.toBufferedImage(imagen).getScaledInstance(w/4, h/4,BufferedImage.TYPE_INT_RGB);
        System.out.println("W:"+w+" H:"+h);
        // mandar un imagen al label
        this.jLabelImagen.
                setIcon(new ImageIcon(escalada));        
        
        BufferedImage biEscalada = 
                herramientas.
                        HerramientasImagen.
                        toBufferedImage(escalada);
        Random ran = new Random();
        // w/4 y h/4
        int rw = ran.nextInt(w/4);
        int rh = ran.nextInt(h/4);
        
        Color color = new Color(biEscalada.getRGB(rw, rh));
        System.out.println("r:"+color.getRed());
        System.out.println("g:"+color.getGreen());
        System.out.println("b:"+color.getBlue());
        // 8,111,7
        
        Color verdeRan = new Color(88,111,6);
        int ce = verdeRan.getRGB();
        // recorremos la imagen
        int contador = 0;
        for(int x=0;x<biEscalada.getWidth();x++){
            for(int y=0;y<biEscalada.getHeight();y++){
                // verificamos la igualdad
                int valorpix = biEscalada.getRGB(x, y);
                if(ce==valorpix){
                    contador++;
                }
            }
        }
        System.out.println("C:"+contador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 355, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // abrir a imagen para poder mandarla
                Image imagen  = 
                        herramientas.HerramientasImagen.
                                abrirImagen();
                new JFrameImagen(imagen).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
